(define (problem combined-default)
    (:domain combined)
    (:init
        (att counter_place)
        (= (total-cost) 0)
        (in water tap)
		(in brownie_mix brownie_bag)
		(in oil oil_bottle)
		(in butter butter_spray_can)
		(in egga egg_shella)
		(in eggb egg_shellb)
		(in pepper pepper_shaker)
		(in salt salt_shaker)
		(in peanut_butter peanut_butter_glass)
		(in jam jam_glass)
		(in pizza_dough pizza_dough_container)
		(in cheese cheese_piece)
		(in pizza_sauce pizza_sauce_can)
		(in salad_sauce salad_sauce_bottle)
		(in crouton crouton_wrapper)
		(is-clean hands)
		(is-clean bowl)
		(is-clean spoon)
		(is-at paper_towela fridge_counter)
        (is-at paper_towelb fridge_counter)
        (is-at pizza_sauce_can_cap pizza_sauce_can)
        (is-at jam_glass_cap jam_glass)
        (is-at peanut_butter_glass_cap peanut_butter_glass)
        (is-at butter_spray_cap butter_spray_can)
        (is-at oil_bottle_cap oil_bottle)
		(is-at egg_box fridge)
		(is-at egg_shellb egg_box)
		(is-at egg_shella egg_box)
		(is-at brownie_bag brownie_box)
		(is-at measuring_cup_s cupboard_tr)
		(is-at measuring_cup_l cupboard_tr)
		(is-at fork drawer)
		(is-at knife drawer)
		(is-at knifeb drawer)
		(is-at whisk drawer)
		(is-at spoon drawer)
		(is-at spatula drawer)
		(is-at board counter)
		(is-at bowl cupboard_tr)
		(is-at brownie_box cupboard_tl)
		(is-at oil_bottle cupboard_br)
		(is-at butter_spray_can cupboard_br)
		(is-at baking_pan cupboard_bl)
		(is-at towel fridge_counter)
		(is-at clip bread_bag)
		(is-at bread_bag cupboard_tl)
		(is-at pepper_shaker cupboard_tl)
		(is-at salt_shaker cupboard_tl)
		(is-at bowl_s cupboard_tl)
		(is-at pan cupboard_bl)
		(is-at plate cupboard_tr)
		(is-at peanut_butter_glass fridge)
		(is-at jam_glass fridge)
		(is-at jam_glass_2 fridge)
		(is-at clip bread_bag)
		(is-at bread_bag cupboard_tl)
        (is-at breada bread_bag)
        (is-at breadb bread_bag)
		(is-at pizza_sauce_can fridge)
		(is-at pizza_dough_container fridge)
		(is-at cheese_wrapper fridge)
		(is-at salami_wrapper fridge)
		(is-at salami salami_wrapper)
		(is-at cheese_piece cheese_wrapper)
		(is-at salad_sauce_bottle fridge)
		(is-at salad_wrapper fridge)
		(is-at celery_wrapper fridge)
		(is-at carrot_wrapper fridge)
		(is-at cucumber_wrapper fridge)
		(is-at crouton_wrapper cupboard_tl)
		(is-at salad salad_wrapper)
		(is-at celery celery_wrapper)
		(is-at carrot carrot_wrapper)
		(is-at cucumber cucumber_wrapper)
		(is-at cutting_board counter)
		(is-at cheese_grater cupboard_bl)
		(is-at peeler drawer)
		(is-open salt_shaker)
		(is-open pepper_shaker)
		(take-pair egg_shella egg_box)
		(take-pair egg_shellb egg_box)
		(take-pair egg_shella counter)
		(take-pair egg_shellb counter)
		(take-pair egg_shella sink)
		(take-pair egg_shellb sink)
		(take-pair egg_shella garbage)
		(take-pair egg_shellb garbage)
		(take-pair egg_shella counter)
		(take-pair egg_shella brownie_box)
		(take-pair egg_shella measuring_cup_l)
		(take-pair egg_shellb counter)
		(take-pair egg_shellb brownie_box)
		(take-pair egg_shellb measuring_cup_l)
		(take-pair baking_pan board)
		(take-pair baking_pan counter)
		(take-pair baking_pan cupboard_bl)
		(take-pair baking_pan oven)
		(take-pair board counter)
		(take-pair bowl counter)
		(take-pair bowl cupboard_tm)
		(take-pair bowl cupboard_tr)
		(take-pair bowl sink)
		(take-pair brownie_bag brownie_box)
		(take-pair brownie_bag counter)
		(take-pair brownie_bag sink)
		(take-pair brownie_bag garbage)
		(take-pair brownie_box garbage)
		(take-pair brownie_box counter)
		(take-pair brownie_box cupboard_br)
		(take-pair brownie_box cupboard_tl)
		(take-pair brownie_box cupboard_tm)
		(take-pair brownie_box sink)
		(take-pair butter_spray_can counter)
		(take-pair butter_spray_cap butter_spray_can)
		(take-pair oil_bottle_cap oil_bottle)
		(take-pair pizza_sauce_can_cap pizza_sauce_can)
		(take-pair jam_glass_cap jam_glass)
		(take-pair peanut_butter_glass_cap peanut_butter_glass)
		(take-pair butter_spray_can butter_spray_cap)
		(take-pair oil_bottle oil_bottle_cap)
		(take-pair pizza_sauce_can pizza_sauce_can_cap)
		(take-pair jam_glass jam_glass_cap)
		(take-pair peanut_butter_glass peanut_butter_glass_cap)
		(take-pair butter_spray_can cupboard_bl)
		(take-pair butter_spray_can cupboard_br)
		(take-pair butter_spray_cap counter)
		(take-pair egg_box counter)
		(take-pair egg_box fridge)
		(take-pair fork bowl)
		(take-pair fork counter)
		(take-pair fork drawer)
		(take-pair fork sink)
		(take-pair fork baking_pan)
		(take-pair knife counter)
		(take-pair knife drawer)
		(take-pair knife plate)
		(take-pair spoon bowl)
		(take-pair knife cutting_board)
		(take-pair cheese_grater cutting_board)
		(take-pair spoon pizza_sauce_can)
		(take-pair fork bowl)
		(take-pair knifeb counter)
		(take-pair knifeb drawer)
		(take-pair measuring_cup_l counter)
		(take-pair measuring_cup_l cupboard_tr)
		(take-pair measuring_cup_l sink)
		(take-pair measuring_cup_s counter)
		(take-pair measuring_cup_s cupboard_tr)
		(take-pair measuring_cup_s sink)
		(take-pair oil_bottle counter)
		(take-pair oil_bottle cupboard_bl)
		(take-pair oil_bottle cupboard_br)
		(take-pair oil_bottle sink)
		(take-pair oil_bottle_cap counter)
		(take-pair paper_towela counter)
		(take-pair paper_towela fridge_counter)
		(take-pair paper_towela sink)
		(take-pair paper_towela garbage)
        (take-pair paper_towelb counter)
		(take-pair paper_towelb fridge_counter)
		(take-pair paper_towelb sink)
		(take-pair paper_towelb garbage)
		(take-pair spatula bowl)
		(take-pair spatula drawer)
		(take-pair spoon bowl)
		(take-pair spoon drawer)
		(take-pair spoon sink)
		(take-pair towel counter)
      	(take-pair towel fridge_counter)
		(take-pair whisk baking_pan)
		(take-pair whisk bowl)
		(take-pair whisk counter)
		(take-pair whisk drawer)
		(take-pair whisk sink)
		(take-pair salt_shaker cupboard_tl)
		(take-pair salt_shaker counter)
		(take-pair salt_shaker board)
		(take-pair salt_shaker stove)
		(take-pair salt_shaker cupboard_tr)
		(take-pair salt_shaker cupboard_br)
		(take-pair salt_shaker cupboard_tm)
		(take-pair salt_shaker cupboard_bl)
		(take-pair salt_shaker drawer)
		(take-pair salt_shaker garbage)
		(take-pair salt_shaker fridge_counter)
		(take-pair pepper_shaker cupboard_tl)
		(take-pair pepper_shaker counter)
		(take-pair pepper_shaker board)
		(take-pair pepper_shaker stove)
		(take-pair pepper_shaker cupboard_tr)
		(take-pair pepper_shaker cupboard_br)
		(take-pair pepper_shaker cupboard_tm)
		(take-pair pepper_shaker cupboard_bl)
		(take-pair pepper_shaker fridge)
		(take-pair pepper_shaker drawer)
		(take-pair pepper_shaker garbage)
		(take-pair pepper_shaker fridge_counter)
		(take-pair plate cupboard_tr)
		(take-pair plate cupboard_tl)
		(take-pair plate cupboard_br)
		(take-pair plate cupboard_tm)
		(take-pair plate cupboard_bl)
		(take-pair plate board)
		(take-pair plate fridge_counter)
		(take-pair plate counter)
		(take-pair plate sink)
		(take-pair plate stove)
		(take-pair pan stove)
		(take-pair pan sink)
		(take-pair pan counter)
		(take-pair pan board)
		(take-pair pan cupboard_bl)
		(take-pair pan cupboard_tr)
		(take-pair pan cupboard_tl)
		(take-pair pan cupboard_br)
		(take-pair pan cupboard_tm)
		(take-pair pan fridge_counter)
		(take-pair fork pan)
		(take-pair bread_bag cupboard_tl)
		(take-pair bread_bag cupboard_tr)
		(take-pair bread_bag cupboard_br)
		(take-pair bread_bag cupboard_tm)
		(take-pair bread_bag cupboard_bl)
		(take-pair bread_bag fridge_counter)
		(take-pair bread_bag board)
		(take-pair bread_bag garbage)
		(take-pair bread_bag sink)
		(take-pair bread_bag counter)
		(take-pair clip counter)
		(take-pair breada bread_bag)
		(take-pair breada board)
		(take-pair breada plate)
		(take-pair breada counter)
		(take-pair breada fridge_counter)
		(take-pair breadb bread_bag)
		(take-pair breadb board)
		(take-pair breadb plate)
		(take-pair breadb counter)
		(take-pair breadb fridge_counter)
		(take-pair peanut_butter_glass fridge)
		(take-pair peanut_butter_glass fridge_counter)
		(take-pair peanut_butter_glass counter)
		(take-pair peanut_butter_glass board)
		(take-pair peanut_butter_glass cupboard_tr)
		(take-pair peanut_butter_glass cupboard_tl)
		(take-pair peanut_butter_glass cupboard_br)
		(take-pair peanut_butter_glass cupboard_tm)
		(take-pair peanut_butter_glass cupboard_bl)
		(take-pair peanut_butter_glass sink)
		(take-pair peanut_butter_glass_cap counter)
		(take-pair peanut_butter_glass_cap fridge_counter)
		(take-pair peanut_butter_glass_cap sink)
		(take-pair jam_glass fridge)
		(take-pair jam_glass fridge_counter)
		(take-pair jam_glass counter)
		(take-pair jam_glass board)
		(take-pair jam_glass cupboard_tr)
		(take-pair jam_glass cupboard_tl)
		(take-pair jam_glass cupboard_br)
		(take-pair jam_glass cupboard_tm)
		(take-pair jam_glass cupboard_bl)
		(take-pair jam_glass sink)
		(take-pair jam_glass_2 fridge)
		(take-pair jam_glass_2 fridge_counter)
		(take-pair jam_glass_2 counter)
		(take-pair jam_glass_cap counter)
		(take-pair jam_glass_cap fridge_counter)
		(take-pair jam_glass_cap sink)
		(take-pair pizza_dough_container fridge)
		(take-pair pizza_dough_container counter)
		(take-pair pizza_dough_container sink)
		(take-pair cheese_wrapper fridge)
		(take-pair cheese_wrapper counter)
		(take-pair cheese_wrapper baking_pan)
		(take-pair cheese_wrapper sink)
		(take-pair cheese_piece cheese_wrapper)
		(take-pair cheese_piece counter)
		(take-pair cheese_piece baking_pan)
		(take-pair salami_wrapper fridge)
		(take-pair salami_wrapper counter)
		(take-pair salami_wrapper sink)
		(take-pair salami_wrapper baking_pan)
		(take-pair salami salami_wrapper)
		(take-pair salami counter)
		(take-pair pizza_sauce_can fridge)
		(take-pair pizza_sauce_can counter)
		(take-pair pizza_sauce_can fridge_counter)
		(take-pair pizza_sauce_can_cap counter)
		(take-pair pizza_sauce_can_cap sink)
		(take-pair spoon pizza_sauce_can)
		(take-pair salami_piecea counter)
		(take-pair salami_piecea cutting_board)
		(take-pair salami_piecea baking_pan)
        (take-pair salami_pieceb counter)
		(take-pair salami_pieceb cutting_board)
		(take-pair salami_pieceb baking_pan)
        (take-pair salami_piecec counter)
		(take-pair salami_piecec cutting_board)
		(take-pair salami_piecec baking_pan)
        (take-pair salami_pieced counter)
		(take-pair salami_pieced cutting_board)
		(take-pair salami_pieced baking_pan)
		(take-pair cheese_grater cupboard_bl)
		(take-pair cheese_grater cutting_board)
		(take-pair cheese_grater counter)
		(take-pair cheese_grater sink)
		(take-pair cheese_grater baking_pan)
		(take-pair cutting_board counter)
		(take-pair salad_sauce_bottle fridge)
		(take-pair salad_sauce_bottle counter)
		(take-pair celery_wrapper fridge)
		(take-pair celery_wrapper counter)
		(take-pair carrot_wrapper fridge)
		(take-pair carrot_wrapper counter)
		(take-pair salad_wrapper fridge)
		(take-pair salad_wrapper counter)
		(take-pair cucumber_wrapper fridge)
		(take-pair cucumber_wrapper counter)
		(take-pair crouton_wrapper cupboard_tl)
		(take-pair crouton_wrapper counter)
		(take-pair cucumber cucumber_wrapper)
		(take-pair cucumber counter)
		(take-pair cucumber cutting_board)
		(take-pair salad salad_wrapper)
		(take-pair salad counter)
		(take-pair salad cutting_board)
		(take-pair salad bowl)
		(take-pair carrot carrot_wrapper)
		(take-pair carrot counter)
		(take-pair carrot cutting_board)
		(take-pair celery celery_wrapper)
		(take-pair celery counter)
		(take-pair celery cutting_board)
		(take-pair peeler drawer)
		(take-pair peeler counter)
		(take-pair peeler cutting_board)
		(take-pair peeler sink)
		(take-pair knife cutting_board)
		(take-pair celery_piecea counter)
		(take-pair celery_piecea cutting_board)
		(take-pair celery_piecea bowl)
        (take-pair celery_pieceb counter)
		(take-pair celery_pieceb cutting_board)
		(take-pair celery_pieceb bowl)
        (take-pair celery_piecec counter)
		(take-pair celery_piecec cutting_board)
		(take-pair celery_piecec bowl)
        (take-pair celery_pieced counter)
		(take-pair celery_pieced cutting_board)
		(take-pair celery_pieced bowl)
		(take-pair cucumber_piecea counter)
		(take-pair cucumber_piecea cutting_board)
		(take-pair cucumber_piecea bowl)
        (take-pair cucumber_pieceb counter)
		(take-pair cucumber_pieceb cutting_board)
		(take-pair cucumber_pieceb bowl)
        (take-pair cucumber_piecec counter)
		(take-pair cucumber_piecec cutting_board)
		(take-pair cucumber_piecec bowl)
        (take-pair cucumber_pieced counter)
		(take-pair cucumber_pieced cutting_board)
		(take-pair cucumber_pieced bowl)
		(take-pair carrot_piecea counter)
		(take-pair carrot_piecea cutting_board)
		(take-pair carrot_piecea bowl)
        (take-pair carrot_pieceb counter)
		(take-pair carrot_pieceb cutting_board)
		(take-pair carrot_pieceb bowl)
        (take-pair carrot_piecec counter)
		(take-pair carrot_piecec cutting_board)
		(take-pair carrot_piecec bowl)
        (take-pair carrot_pieced counter)
		(take-pair carrot_pieced cutting_board)
		(take-pair carrot_pieced bowl)
		(take-pair celery_piecea sink)
		(take-pair carrot_piecea sink)
		(take-pair cucumber_piecea sink)
        (take-pair celery_pieceb sink)
		(take-pair carrot_pieceb sink)
		(take-pair cucumber_pieceb sink)
        (take-pair celery_piecec sink)
		(take-pair carrot_piecec sink)
		(take-pair cucumber_piecec sink)
        (take-pair celery_pieced sink)
		(take-pair carrot_pieced sink)
		(take-pair cucumber_pieced sink)
		(fill-triple brownie_mix brownie_bag bowl)
		(fill-triple butter butter_spray_can baking_pan)
		(fill-triple butter butter_spray_can measuring_cup_s)
		(fill-triple butter measuring_cup_s bowl)
		(fill-triple dough bowl baking_pan)
		(fill-triple egga egg_shella bowl)
		(fill-triple eggb egg_shellb bowl)
		(fill-triple egga bowl pan)
		(fill-triple eggb bowl pan)
		(fill-triple oil measuring_cup_s bowl)
		(fill-triple oil oil_bottle measuring_cup_s)
		(fill-triple water measuring_cup_l bowl)
		(fill-triple water tap measuring_cup_l)
		(fill-triple eggs bowl pan)
		(fill-triple eggs bowl_s pan)
		(fill-triple eggs pan plate)
		(fill-triple pepper pepper_shaker bowl)
		(fill-triple pepper pepper_shaker pan)
		(fill-triple pepper pepper_shaker bowl_s)
		(fill-triple salt salt_shaker bowl)
		(fill-triple salt salt_shaker pan)
		(fill-triple salt salt_shaker bowl_s)
		(fill-triple oil oil_bottle pan)
		(fill-triple peanut_butter peanut_butter_glass breada)
		(fill-triple jam jam_glass breada)
		(fill-triple pizza_dough pizza_dough_container baking_pan)
		(fill-triple pizza_dough pizza_dough_container cutting_board)
		(fill-triple pizza_dough cutting_board baking_pan)
		(fill-triple pizza_sauce pizza_sauce_can baking_pan)
		(fill-triple cheese cheese_piece baking_pan)
		(fill-triple cheese cheese_piece cutting_board)
		(fill-triple cheese cutting_board baking_pan)
		(fill-triple salad_sauce salad_sauce_bottle bowl)
		(fill-triple crouton crouton_wrapper bowl)
		(turn-single stove)
		(turn-single oven)
		(stir-pair bowl whisk)
		(stir-pair bowl spatula)
		(stir-pair bowl spoon)
		(stir-pair bowl fork)
		(stir-pair pan whisk)
		(stir-pair pan spatula)
		(stir-pair pan spoon)
		(stir-pair pan fork)
		(clean-pair hands towel)
		(clean-pair hands paper_towela)
		(clean-pair knife towel)
		(clean-pair knife paper_towela)
		(clean-pair spoon towel)
		(clean-pair spoon paper_towela)
		(clean-pair cheese_wrapper towel)
		(clean-pair cheese_wrapper paper_towela)
		(clean-pair pan towel)
		(clean-pair pan paper_towela)
		(clean-pair bowl towel)
		(clean-pair bowl paper_towela)
		(cook-triple eggs pan stove)
		(shake-single jam_glass)
		(shake-single butter_spray_can)
		(shake-single pan)
		(shake-single baking_pan)
		(shake-single salad_sauce_bottle)
		(cut-pair salami counter)
		(cut-pair salami cutting_board)
		(cut-pair carrot counter)
		(cut-pair carrot cutting_board)
		(cut-pair carrot bowl)
		(cut-pair cucumber counter)
		(cut-pair cucumber cutting_board)
		(cut-pair cucumber bowl)
		(cut-pair celery counter)
		(cut-pair celery cutting_board)
		(cut-pair celery bowl)
		(peel-pair carrot peeler)
		(peel-pair carrot knife)
		(peel-pair cucumber peeler)
		(peel-pair cucumber knife)
		(unroll-single pizza_dough)
		(rinse-single salad)
)
	(:goal (and
                (made_pizza)
            )
    )
    (:metric minimize (total-cost))
)